name: CI Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Local MySQL for Tests
        run: docker compose up -d
      - name: Build
        run: lein deps
      - name: Run Migrations
        run: lein run migrations
      - name: Run tests
        run: lein tests
      - name: Stop MySQL
        run: docker compose down -v
