name: CI Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Local MySQL and run tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
        run: |
          lein deps
          lein run migrations
          lein test
